### PR TITLE
Add CreateTable method to ChunkStore.

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by tomwilkie** [comment]
How did you envoke this?  Can we make it flag controlled?

**Comment by juliusv** [comment]
Oh, the test program I have just invokes it every time, but we can totally control that in any way we want. Or leave it out of the AWSChunkStore code completely if you prefer to have some external script create the table.

**Comment by juliusv** [comment]
@tomwilkie Is this cool to merge for now? The control over when this method is called is left up to the user of the type.

**Comment by tomwilkie** [comment]
Superceeded by #19

**Pull request closed without merging**
